require('angular');
require('angular-i18n/ar');
require('angular-ui-bootstrap');
require('./polyfill');
require('./locale/config')
require('./components/clients/clients.component.js');
require('./components/client-modal/client-modal.component.js');
require('./components/delete-client-modal/delete-client-modal.component.js');
require('./components/controls/controls.component.js');
require('./components/header/header.component.js');
require('./components/layout/layout.component.js');
require('./components/notifications/notifications.component.js');